package com.ashwin.tickettoride.enums;

public enum City {
    VANCOUVER, SEATTLE, PORTLAND, SAN_FRANCISCO, LOS_ANGELES, LAS_VEGAS, PHOENIX,
    EL_PASO, OKLAHOMA_CITY, DALLAS, HOUSTON, NEW_ORLEANS, MIAMI, ATLANTA,
    CHARLESTON, RALEIGH, WASHINGTON, NEW_YORK, BOSTON, MONTREAL, TORONTO,
    CHICAGO, SAINT_LOUIS, KANSAS_CITY, DENVER, SALT_LAKE_CITY, HELENA,
    CALGARY, WINNIPEG, SAULT_ST_MARIE, DULUTH, OMAHA, LITTLE_ROCK, NASHVILLE,
    PITTSBURGH
}